[package]
name = "rocket-util"
version = "0.2.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"

[dependencies.ics]
version = "0.5"
default-features = false
optional = true

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]
optional = true

[dependencies.rocket_csrf]
git = "https://github.com/fenhl/rocket_csrf"
branch = "impl-error"
optional = true

[dependencies.rocket-util-derive]
path = "../rocket-util-derive"
